[versions]
ksp = "2.3.9"
kotest = "6.1.11"
kotlin = "2.4.0"
ktlint = "1.8.0"
slf4j = "2.0.18"

[libraries]
# KSP and code generation
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
auto-service-annotations = "com.google.auto.service:auto-service-annotations:1.1.1"
kotlinpoet-ksp = "com.squareup:kotlinpoet-ksp:2.3.0"
auto-service-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.2.0"
ktlint-rule-engine = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint" }
ktlint-ruleset-standard = { module = "com.pinterest.ktlint:ktlint-ruleset-standard", version.ref = "ktlint" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j" }

# Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

# Kotlin
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.8.0"
swagger-parser = "io.swagger.parser.v3:swagger-parser:2.1.37"

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version = "0.54.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotest = { id = "io.kotest", version.ref = "kotest" }
dokka = { id = "org.jetbrains.dokka", version = "2.2.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.3.0" }

