[versions]
ksp = "2.3.5"
kotest = "6.1.2"
jetbrains-kotlin = "2.3.0"

[libraries]
# KSP and code generation
ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
auto-service-annotations = "com.google.auto.service:auto-service-annotations:1.1.1"
kotlinpoet-ksp = "com.squareup:kotlinpoet-ksp:2.2.0"
auto-service-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.2.0"

# Kotest
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

# Kotlin
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "jetbrains-kotlin" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "jetbrains-kotlin" }
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0"

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
kotest = { id = "io.kotest", version.ref = "kotest" }
dokka = { id = "org.jetbrains.dokka", version = "2.1.0" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jetbrains-kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "5.3.0" }

