package xyz.dussim.buildlogic

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.double
import kotlinx.serialization.json.jsonObject
import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.SkipWhenEmpty
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.assign
import org.gradle.kotlin.dsl.create
import org.gradle.work.DisableCachingByDefault
import java.io.File

abstract class GenerateFeatureJsonTestsPlugin : Plugin<Project> {
    override fun apply(target: Project): Unit =
        target.run {
            val extension = extensions.create<GenerateFeatureJsonTestsExtension>("generateFeatureJsonTests")
            tasks.register(
                "generateFeatureJsonTests",
                GenerateFeatureJsonTestsTask::class.java,
            ) {
                generatedJsons = extension.generatedJsons
                generatedTests = extension.generatedTests
            }
        }
}

abstract class GenerateFeatureJsonTestsExtension {
    abstract val generatedJsons: DirectoryProperty

    abstract val generatedTests: DirectoryProperty
}

@DisableCachingByDefault
abstract class GenerateFeatureJsonTestsTask : DefaultTask() {
    companion object {
        private val pattern = "(?<!_)0(?=[A-Za-z])".toRegex()
        private val temporarilyDisabledTests = setOf<String>()
    }

    @get:InputDirectory
    @get:SkipWhenEmpty
    abstract val generatedJsons: DirectoryProperty

    @get:OutputDirectory
    abstract val generatedTests: DirectoryProperty

    init {
        group = "build"
        description = "Generates Kotest test files for each generated feature JSON"
    }

    private val json = Json

    @TaskAction
    fun generate() {
        val inputDir = generatedJsons.get().asFile
        val outputDir = generatedTests.get().asFile
        outputDir.deleteRecursively()
        outputDir.mkdirs()

        val packageDir = outputDir.resolve("xyz/dussim/viessmann/api/features/generated")
        packageDir.mkdirs()

        val jsonFiles =
            inputDir
                .listFiles { file -> file.extension == "json" && file.name != "all_features.json" }
                ?.sortedBy { it.name }
                ?: emptyList()

        logger.lifecycle("Generating tests for ${jsonFiles.size} feature JSON files")

        // One Spec per top-level feature group (first dot-segment of the feature name).
        // Each Spec contains one test(...) per feature in that group.
        val grouped = jsonFiles.groupBy { groupNameOf(it.nameWithoutExtension) }

        for ((groupName, files) in grouped.toSortedMap()) {
            val specClassName = "${groupName.replaceFirstChar { it.uppercase() }}FeaturesJsonTest"
            val testContent = buildSpecFile(specClassName, files)
            packageDir.resolve("$specClassName.kt").writeText(testContent)
        }

        logger.lifecycle("Generated ${grouped.size} spec files (${jsonFiles.size} tests total) in: $outputDir")
    }

    private fun groupNameOf(featureName: String): String {
        val firstSegment = featureName.substringBefore('.').ifEmpty { "misc" }
        // Sanitize to a valid identifier suffix; first segment in this codebase is already a plain word
        // (e.g. heating, pcc, autogenerated), but be defensive against unexpected characters.
        return firstSegment.replace(pattern, "N").replace(Regex("[^A-Za-z0-9_]"), "_")
    }

    private fun featureClassNameOf(baseName: String): String {
        val sanitized = baseName.replace(pattern, "N")
        return sanitized
            .replace(".0", ".N")
            .split(".")
            .joinToString("") { it.replaceFirstChar { c -> c.uppercase() }.replace(pattern, "N") } + "Feature"
    }

    private fun buildSpecFile(
        specClassName: String,
        files: List<File>,
    ): String =
        buildString {
            appendLine("package xyz.dussim.viessmann.api.features.generated")
            appendLine()
            appendLine("import de.infix.testBalloon.framework.core.testSuite")
            appendLine()
            append(
                """
                @Suppress(
                    "ktlint:standard:class-naming",
                    "ktlint:standard:max-line-length",
                    "ClassName",
                    "RedundantSuppression",
                    "RemoveRedundantBackticks",
                    "UNNECESSARY_SAFE_CALL",
                )
                """.trimIndent(),
            )
            appendLine()
            appendLine("val $specClassName by testSuite {")
            files.sortedBy { it.name }.forEach { jsonFile ->
                appendFeatureTest(jsonFile)
            }
            appendLine("}")
        }

    private fun StringBuilder.appendFeatureTest(jsonFile: File) {
        val baseName = jsonFile.nameWithoutExtension
        val className = featureClassNameOf(baseName)
        val resourcePath = jsonFile.name
        val isTemporarilyDisabled = baseName in temporarilyDisabledTests
        val featureJson = json.parseToJsonElement(jsonFile.readText()).jsonObject
        val assertions = buildAssertions(featureJson)
        val testFn = if (isTemporarilyDisabled) "xtest" else "test"
        if (isTemporarilyDisabled) {
            appendLine("        // Disabled for now: these generated tests are not working due to issues with the underlying data.")
        }
        appendLine("        $testFn(\"Parse $baseName as $className\") {")
        appendLine("            featureJsonTest(\"$resourcePath\", $className.descriptor) {")
        assertions.forEach { assertion ->
            appendLine("                $assertion")
        }
        appendLine("            }")
        appendLine("        }")
    }

    private fun buildAssertions(featureJson: JsonObject): List<String> =
        buildList {
            addAll(buildPropertyAssertions(featureJson["properties"] as? JsonObject ?: return@buildList))
            addAll(buildCommandAssertions(featureJson["commands"] as? JsonObject ?: JsonObject(emptyMap())))
        }

    private fun buildPropertyAssertions(properties: JsonObject): List<String> =
        properties
            .entries
            .sortedBy { it.key }
            .mapNotNull { (name, property) ->
                val propertyObject = property as? JsonObject ?: return@mapNotNull null
                val value = propertyObject["value"] ?: return@mapNotNull null
                if (value is JsonArray && value.isEmpty()) return@mapNotNull null
                val literal = valueLiteral(value) ?: return@mapNotNull null
                "${accessor(name)} shouldHaveElement $literal"
            }

    private fun buildCommandAssertions(commands: JsonObject): List<String> =
        commands.entries.sortedBy { it.key }.flatMap { (name, command) ->
            val commandObject = command as? JsonObject ?: return@flatMap emptyList()
            val commandAccessor = accessor(name)
            buildList {
                val commandName = stringValue(commandObject, "name")
                val isExecutable = booleanValue(commandObject, "isExecutable")
                val uri = stringValue(commandObject, "uri")
                if (commandName != null && isExecutable != null && uri != null) {
                    add("$commandAccessor.shouldHaveCommand(${kotlinString(commandName)}, $isExecutable, ${kotlinString(uri)})")
                }

                val params = commandObject["params"] as? JsonObject ?: return@buildList
                params.entries.sortedBy { it.key }.forEach { (paramName, param) ->
                    val paramObject = param as? JsonObject ?: return@forEach
                    val constraints = paramObject["constraints"] as? JsonObject ?: JsonObject(emptyMap())
                    buildConstraintAssertion("$commandAccessor?.${accessor(paramName)}", paramObject, constraints)?.let(::add)
                }
            }
        }

    private fun buildConstraintAssertion(
        accessor: String,
        parameter: JsonObject,
        constraints: JsonObject,
    ): String? =
        when (val type = stringValue(parameter, "type")) {
            "string" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveStringConstraints",
                    constraints,
                    listOf("minLength", "maxLength", "regEx", "enum", "sameDayAllowed"),
                )
            }

            "number", "integer" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveNumberConstraints",
                    constraints,
                    listOf("min", "efficientLowerBorder", "efficientUpperBorder", "max", "stepping", "enum"),
                )
            }

            "array" -> {
                arrayConstraintFunctionCall(accessor, constraints)
            }

            "array:string" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveArrayStringConstraints",
                    constraints,
                    listOf("minLength", "maxLength", "enum"),
                )
            }

            "array:number" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveArrayNumberConstraints",
                    constraints,
                    listOf("minLength", "maxLength", "enum"),
                )
            }

            "array:boolean" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveArrayBooleanConstraints",
                    constraints,
                    listOf("minLength", "maxLength", "enum"),
                )
            }

            "object" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveObjectConstraints",
                    constraints,
                    listOf("minProperties", "maxProperties", "required"),
                )
            }

            "Schedule" -> {
                constraintFunctionCall(
                    accessor,
                    "shouldHaveScheduleConstraints",
                    constraints,
                    listOf("modes", "maxEntries", "resolution", "defaultMode", "overlapAllowed"),
                )
            }

            else -> {
                logger.debug("Skipping assertions for unsupported parameter type '$type'")
                null
            }
        }

    private fun constraintFunctionCall(
        accessor: String,
        functionName: String,
        constraints: JsonObject,
        fields: List<String>,
    ): String? {
        val integerFields = setOf("minLength", "maxLength", "minProperties", "maxProperties", "maxEntries", "resolution")
        val arguments =
            fields.map { field ->
                val value = constraints[field] ?: JsonNull
                val literal =
                    if (field in integerFields) {
                        intValueLiteral(value) ?: return null
                    } else {
                        valueLiteral(value) ?: return null
                    }
                "$field = $literal"
            }
        return "$accessor.$functionName(${arguments.joinToString()})"
    }

    private fun arrayConstraintFunctionCall(
        accessor: String,
        constraints: JsonObject,
    ): String? {
        val enum = constraints["enum"] as? JsonArray
        val functionName =
            when (val firstEnumValue = enum?.firstOrNull()) {
                is JsonPrimitive -> {
                    when {
                        firstEnumValue.isString -> "shouldHaveArrayStringConstraints"
                        firstEnumValue.booleanOrNull != null -> "shouldHaveArrayBooleanConstraints"
                        else -> "shouldHaveArrayNumberConstraints"
                    }
                }

                else -> {
                    return null
                }
            }
        return constraintFunctionCall(
            accessor = accessor,
            functionName = functionName,
            constraints = constraints,
            fields = listOf("minLength", "maxLength", "enum"),
        )
    }

    private fun valueLiteral(value: JsonElement): String? =
        when (value) {
            JsonNull -> "null"
            is JsonPrimitive -> primitiveLiteral(value)
            is JsonArray -> arrayLiteral(value)
            is JsonObject -> null
        }

    private fun arrayLiteral(array: JsonArray): String? {
        if (array.isEmpty()) return "emptyList<Nothing>()"

        val literals = array.map { valueLiteral(it) ?: return null }
        return "listOf(${literals.joinToString()})"
    }

    private fun intValueLiteral(value: JsonElement): String? =
        when (value) {
            JsonNull -> "null"
            is JsonPrimitive -> primitiveIntLiteral(value)
            else -> null
        }

    private fun primitiveIntLiteral(primitive: JsonPrimitive): String =
        when {
            primitive.isString -> primitive.content.toInt().toString()
            primitive.booleanOrNull != null -> error("Cannot render boolean as integer literal: $primitive")
            else -> primitive.double.toInt().toString()
        }

    private fun primitiveLiteral(primitive: JsonPrimitive): String =
        when {
            primitive.isString -> kotlinString(primitive.content)
            primitive.booleanOrNull != null -> primitive.booleanOrNull.toString()
            else -> primitive.double.toString()
        }

    private fun stringValue(
        jsonObject: JsonObject,
        name: String,
    ): String? = (jsonObject[name] as? JsonPrimitive)?.content

    private fun booleanValue(
        jsonObject: JsonObject,
        name: String,
    ): Boolean? = (jsonObject[name] as? JsonPrimitive)?.booleanOrNull

    private fun accessor(name: String): String = "`$name`"

    private fun kotlinString(value: String): String =
        buildString {
            append('"')
            value.forEach { char ->
                when (char) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '$' -> append("\\$")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    '\b' -> append("\\b")
                    else -> append(char)
                }
            }
            append('"')
        }
}
