{
  "steps": [
    {
      "name": "jvmTest",
      "image": "dussim/build-env:jdk26_gradle-9.6.0-rc3",
      "commands": [
        "gradle jvmTest --scan"
      ],
      "when": {
        "event": "push"
      }
    }
  ]
}